/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:872dba89-08c0-4dad-83e8-9b595d955ba7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3bwICZRYM",
    "aws_user_pools_web_client_id": "6hej5cgm4so7gd4cnul1slsu5k",
    "oauth": {},
    "aws_user_files_s3_bucket": "thisorthatimagebucketthat-test",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://3n5vezc4yjby7ogmg236oaqgou.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rchxf23icretpjhlruriy53eiq"
};


export default awsmobile;
